/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'
import { Route as RiderApplyRouteImport } from './routes/rider.apply'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderApplyRoute = RiderApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => RiderRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/rider': typeof RiderRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rider/apply': typeof RiderApplyRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rider/apply': typeof RiderApplyRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/rider': typeof RiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/rider': typeof RiderRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rider/apply': typeof RiderApplyRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/rider'
    | '/search'
    | '/sitemap.xml'
    | '/orders/$orderNumber'
    | '/products/$slug'
    | '/rider/apply'
    | '/sectors/$slug'
    | '/rider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/sitemap.xml'
    | '/orders/$orderNumber'
    | '/products/$slug'
    | '/rider/apply'
    | '/sectors/$slug'
    | '/rider'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/rider'
    | '/search'
    | '/sitemap.xml'
    | '/orders/$orderNumber'
    | '/products/$slug'
    | '/rider/apply'
    | '/sectors/$slug'
    | '/rider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  RiderRoute: typeof RiderRouteWithChildren
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/apply': {
      id: '/rider/apply'
      path: '/apply'
      fullPath: '/rider/apply'
      preLoaderRoute: typeof RiderApplyRouteImport
      parentRoute: typeof RiderRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RiderRouteChildren {
  RiderApplyRoute: typeof RiderApplyRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderApplyRoute: RiderApplyRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  RiderRoute: RiderRouteWithChildren,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SectorsSlugRoute: SectorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
